### ISSUE TITLE
instructions should say new not init

### ISSUE THREAD

**Issue by wynged** [hypar-io/function#2]
in the readme the instructions say that `hypar init` will clone thie generator repo, but the command should be `hypar new`

**Comment by wynged** [comment]
Also, later on when it says to run `hypar init` that is the correct command, but init needs a directory argument, so I think it should say `hypar init src` if using the template.  if the user doesn't choose 'src' or the correct directory, then the input and output .g.cs files don't end up in the right spot.

**Comment by ikeough** [comment]
This is now fixed in the docs. Thanks @wynged!
