### ISSUE TITLE
function tests don't work with new hypar-cli... generator github repo is out of date?

### ISSUE THREAD

**Issue by wynged** [hypar-io/function#3]
I might just be missing something but... while upgrading to utse the new elements library I needed to upgrade a function by re-running`hypar init` and ran into problems. Thought I could get through it, realized I needed new Amazon references for `using Amazon.S3` to work.  Guessed and got the latest using `dotnet add package AWSSDK.S3`

However, there are still things wrong with my now outdated test methods.  This test method is from the old generator and doesn't work.  I think this Generator repo is old.  Generating new hypar funcs also doesn't work (which makes sense, because it just clones this repo)

If i'm right that this repo is out of date updating this repo would be great.  It looks like I should start using `output.Result` for the computed properties as well as the model.  

However, these changes get me to a successful build, but not a successful test. The JSON deserialization of the sample data at the top of the test fails.  It's not in the correct format.  GUIDs where there should be Int64s... bummer.

here's the code where I replaced `output["Element_count"]` with `output.Result.Element_count` and similar changes to get a good build
```C#
        [Fact]
        public void Test()
        {
            // Execute the function.
            var func = new Function();
            var output = func.Handler(_data, null);

            Assert.NotNull(_data.Model);

            // Check that the computed values are as expected.
        
            var computed = (Dictionary<string,object>)output["computed"];
            Assert.True(Math.Abs((double)computed["element_count"]) > 0.0);

            var model = Model.FromJson(output["elements"].ToString());
            model.SaveGltf("model.gltf");
```

**Comment by ikeough** [comment]
Apologies for the delay in picking this up. I believe this has now been brought up to date with the latest and greatest that the CLI creates. Can you verify that this repo's test functions as expected?

**Comment by wynged** [comment]
ok, looks better / different, not able to get a test though...

- `hypar new mister-web-system`
- remove the .git stuff, don't need in my repo situation
- remove license, preview, readme stuf
- edit hypar.json
- run `hypar init src`  NOTE: instructions should say to run `hypar init` with `src`
- restart VSCode, seems like build can't find the new Input.g.cs files
- !!! function.csproj wont' build  !!!
- problems in `Function.g.cs`
  - missing `using Elements.Serialization.glTF;` and `using Elements.Serialization.JSON;`
  -wrong serialization method.  It doesn't seem ready for Elements version 0.2.2. line 56  `model.SaveGlb` is deprecated, and the new method is `model.ToGlTF` with a parameter for serializing to binary.  
- problems in `Input.g.cs` 
  - wrong namespace for ModelConverter line 55.  needs to be `Elements.Serialization.JSON.ModelConverter`
- The HyparDotnetStarter.cs file exists... with errors... and I don't think I need it, so I deleted it.  would be nice if it wasn't there.
  - `function.csproj` builds, yay!
- `function-test.csproj` won't build :-(
- problem in `FunctionTest.cs`
  - the namespace of my function is missing, had to add it to access `Input` class
  - needed to comment out the assert in the test function, because `output.Area` is no longer valid with my edits to hypar.json
- can now run `dotnet test` from top directory without build errors
- Test fails!!!  
  - steping through as far as line 39 in `Function.g.cs` error in UploatGlTFAsync occurs because `output.Model` was not set in my function...
    - for my test function I simply had `return new Output(input.Model, 0);` passing a model straight through, this resulted in null value error
    - creating a new model and adding that to the output instead seemed better... this particular problem makes sense now, although currently there's no way there is a model on the "Input" so maybe that property shouldn't exist? 
  - now have a problem still in `model.ToGlTF()` lin 57 in Function.g.cs, expcted buffer size > 0 ???
    - Ok, add a space to the fake model I've created, that gets to next error
  - part of filepath writing to `../../../live/models/model.glb` doesn't exist.  yup, the models directory doesn't exist
    - make that directory

Test Passes!!!  phew!

In the end, got it to run.  These are all my notes of the process I went through hope it helps.  Adding actually interesting function code next :-)

**Comment by ikeough** [comment]
Thanks Eric! I think many of these issues arise from the fact that we don’t generate test infrastructure, which would be a really smart thing for us to do ;) Code generation by the CLI and cloning the repo from github are currently in opposition. I’ll smooth this out.

Ian Keough

@ikeough

**Comment by wynged** [comment]
you've done great work with the function and test generator with the CLI
